name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore "./ServerlessWorkflow.Sdk.sln"
    - name: Build
      run: dotnet build "./ServerlessWorkflow.Sdk.sln" --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test "./ServerlessWorkflow.Sdk.sln" --no-restore --verbosity detailed
    - name: Push1
      run: dotnet nuget push "./src/*/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
